ci:
    skip: [ruff, pyright]

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-install

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]

      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.369
    hooks:
    - id: pyright
