site_name: Gen ⊗ JAX
site_url: https://probcomp.github.io/genjax/
repo_url: https://github.com/probcomp/genjax
copyright: Copyright &copy; 2023 MIT Probabilistic Computing Project
nav:
  - Home: index.md
  - Concepts:
      - Diff with Gen.jl: genjax/diff_jl.md
  - Inference notebooks: genjax/notebooks.md
  - Public API reference:
      - Core: genjax/library/core.md
      - Generative functions: genjax/library/generative_functions.md
      - Inferece: genjax/library/inference.md
  - For developers:
      - Code of conduct: codeofconduct.md
      - Contributing: contributing.md
      - License: license.md
theme:
  name: material
  font:
    text: Atkinson Hyperlegible
    code: Fira Code
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - header.autohide
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - offline
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false

extra:
  generator: false

extra_css: [css/custom.css]

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
