# Copyright 2022 MIT Probabilistic Computing Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: GenJAX
site_url: https://chisym.github.io/genjax/
repo_url: https://github.com/chisym/genjax
repo_name: chisym/genjax
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 MIT Probabilistic Computing Project

nav:
  - Home: index.md
  - Cookbook:
      - Just starting out:
          - JAX basics: cookbook/active/jax_basics.ipynb
          - Introduction: cookbook/active/intro.ipynb
          - The generative function interface: cookbook/active/generative_function_interface.ipynb
          - Working with choice maps: cookbook/active/choice_maps.ipynb
          - Debugging: cookbook/active/debugging.ipynb

      - Still being tidied:
          - Generative functions: cookbook/inactive/generative_fun.ipynb

          - Expressivity:
              - cookbook/inactive/expressivity/conditionals.ipynb
              - cookbook/inactive/expressivity/iterating_computation.ipynb
              - cookbook/inactive/expressivity/masking.ipynb
              - cookbook/inactive/expressivity/mixture.ipynb
              - cookbook/inactive/expressivity/custom_distribution.ipynb
              - cookbook/inactive/expressivity/stochastic_probabilities.ipynb
              - cookbook/inactive/expressivity/stochastic_probabilities_math.ipynb

          - Inference:
              - Importance sampling: cookbook/inactive/inference/importance_sampling.ipynb
              - Custom proposal: cookbook/inactive/inference/custom_proposal.ipynb
              - MCMC: cookbook/inactive/inference/mcmc.ipynb

          - Differentiation:
              - ADEV Example: cookbook/inactive/differentiation/adev_example.py

          - Speed:
              - Update:
                - Importance: cookbook/inactive/update/1_importance.ipynb
                - Update: cookbook/inactive/update/2_update.ipynb

          - Library developers:
              - Dimap combinator: cookbook/inactive/library_author/dimap_combinator.ipynb

  - Library reference:
      - Core: library/core.md
      - Generative functions: library/generative_functions.md
      - Combinators: library/combinators.md
      - Inference: library/inference.md
  - For developers:
      - Developing: developing.md
      - Code of conduct: codeofconduct.md
      - Contributing: contributing.md
      - License: license.md

theme:
  name: material
  logo: assets/img/small_logo.png
  favicon: assets/img/gen-logo.png
  font:
      text: Roboto
      code: Berkeley Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - optimize
    - typeset
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: red
      primary: white

watch:
  - src/genjax

plugins:
  - search
  - offline
  - markdown-exec
  - mkdocs-jupyter:
        execute: true
        allow_errors: false
        ignore:
         # TODO: re-enable once we can support marginals as targets
          - "cookbook/inactive/expressivity/ravi_stack.ipynb"
          - "cookbook/inactive/differentiation/adev_demo.py"

        highlight_extra_classes: "custom-css-classes"
  - typeset:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          options:
            group_by_category: true
            show_symbol_type_toc: true
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            parameter_headings: true
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
            summary: true

extra:
  generator: false
  version:
    provider: mike

extra_css:
  - css/custom.css
  - css/mkdocstrings.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
      - name: python
        class: python
        validator: !!python/name:markdown_exec.validator
        format: !!python/name:markdown_exec.formatter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: On this page
      toc_depth: 3
      permalink: true
