project:
  title: 'GenJAX Jupyter notebooks'
  output-dir: ../site/notebooks
  type: website

author: McCoy Reynolds Becker

website:
  title: 'Gen ⊗ JAX'
  search:
    location: sidebar
    type: textbox
  open-graph: true
  page-navigation: true
  repo-url: https://github.com/probcomp/genjax
  repo-actions: [edit, issue]

  sidebar:
    logo: logo.png
    style: 'floating'
    border: true
    pinned: true
    align: center
    collapse-level: 1
    tools:
      - icon: house-heart
        href: /
        text: 'Home'
      - icon: building
        href: http://probcomp.csail.mit.edu/
        text: 'MIT Probabilistic Computing Project'
      - icon: github
        href: https://github.com/probcomp/genjax
        text: 'GitHub repository'
    contents:
      - section: 'Getting started'
        contents:
          - href: concepts/introduction/intro_to_genjax.ipynb
            text: Introduction

          - href: concepts/introduction/intro_interpreted.ipynb
            text: Introduction (interpreted dialect)

          - href: concepts/incremental_computation/incremental.ipynb
            text: (WIP) Incremental computing

      - section: 'Sequential Monte Carlo (SMC)'
        contents:
          - href: advanced/smc_language/smc_language.ipynb
            text: 'The sequential Monte Carlo mini-language'

          - href: intermediate/smc/smc_with_translators.ipynb
            text: 'SMC with Translators'

      - section: 'Internals'
        contents:
          - href: internals/developers/jax_intro.ipynb
            text: "Developers' intro to JAX"

  page-footer:
    center: © Copyright 2022-2024 [MIT Probabilistic Computing Project](http://probcomp.csail.mit.edu/)

toc: true
toc-location: right
reference-location: margin
citation-location: margin

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: breeze
