project:
  type: book
  output-dir: ../site/cookbook

book:
  title: "The GenJAX cookbook"
  favicon: small_logo.png
  image: small_logo.png
  repo-url: https://github.com/probcomp/genjax/
  repo-branch: main
  repo-subdir: notebooks
  repo-actions: [issue, source]
  sidebar:
    background: "#F5F5F5"
    logo: small_logo.png
    search: true
    style: 'floating'
  chapters:
    - index.ipynb
    # - jax_primer.ipynb
    - active/intro.ipynb
    # - combinators.ipynb
    # - inference_libraries.ipynb
    - cookbook/basics/generative_fun.ipynb
    - cookbook/basics/methods_of_generative_fun.ipynb
    - cookbook/basics/debugging.ipynb
    - cookbook/basics/saving_traces.ipynb
    - cookbook/basics/some_oddities.ipynb
    - cookbook/expressivity/conditionals.ipynb
    - cookbook/expressivity/iterating_computation.ipynb
    - cookbook/expressivity/mixture.ipynb
    - cookbook/expressivity/custom_distribution.ipynb
    - cookbook/inference/importance_sampling.ipynb
    - cookbook/inference/custom_proposal.ipynb
    - cookbook/inference/mcmc.ipynb
    - cookbook/library_author/dimap_combinator.ipynb

bibliography: references.bib

format:
  html:
    css: custom.css
    theme: cosmo
    title-block-banner: true
    code-copy: true
    cold-fold: false
    code-overflow: wrap
    highlight-style: ayu
    backgroundcolor: "#F5F5F5"
    logo: ../docs/assets/img/logo.png
