project:
  type: book
  output-dir: ../site/cookbook

book:
  title: "The GenJAX cookbook"
  author: "The GenJAX authors"
  favicon: small_logo.png
  image: small_logo.png
  repo-url: https://github.com/probcomp/genjax/
  repo-branch: main
  repo-subdir: notebooks
  repo-actions: [issue, source]
  sidebar:
    background: "#F5F5F5"
    logo: small_logo.png
    search: true
    style: 'floating'
  chapters:
    - index.ipynb
    # - jax_primer.ipynb
    - active/intro.ipynb
    # - combinators.ipynb
    # - inference_libraries.ipynb

bibliography: references.bib

format:
  html:
    css: custom.css
    theme: cosmo
    title-block-banner: false
    code-copy: true
    cold-fold: false
    code-overflow: wrap
    highlight-style: ayu
    backgroundcolor: "#F5F5F5"
    logo: ../docs/assets/img/logo.png
