project:
  type: book
  output-dir: ../site/cookbook

book:
  title: "The GenJAX cookbook"
  author: "The GenJAX authors"
  favicon: small_logo.png
  image: small_logo.png
  repo-url: https://github.com/probcomp/genjax/
  repo-branch: main
  repo-subdir: notebooks
  repo-actions: [edit, issue, source]
  sidebar:
    background: "#F5F5F5"
    logo: small_logo.png
    search: true
    style: 'floating'
  chapters:
    - index.qmd
    - intro.qmd
    - inference_libraries.qmd

bibliography: references.bib

format:
  html:
    css: custom.css
    theme: cosmo
    code-copy: true
    cold-fold: false
    code-overflow: wrap
    highlight-style: kate
    backgroundcolor: "#F5F5F5"
    logo: ../docs/assets/img/logo.png
