project:
  title: "GenJAX Jupyter notebooks"
  output-dir: ../_build/notebooks
  type: website

website:
  title: "Gen ⊗ JAX"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  search:
    location: navbar
    type: overlay

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - introduction/intro_to_genjax/intro_to_genjax.ipynb
      - section: "Advanced"
        contents:
          - advanced/pseudomarginal_smc/pseudomarginal_smc.ipynb

author: McCoy Reynolds Becker
theme:
  - cosmo
  - custom.scss

toc: true
format:
  html:
    code-fold: false
    self-contained: true
    code-tools: true
    code-overflow: wrap

reference-location: margin
citation-location: margin
