project:
  title: 'GenJAX Jupyter notebooks'
  output-dir: ../_build/notebooks
  type: website

author: McCoy Reynolds Becker

website:
  title: 'Gen ⊗ JAX'
  search:
    location: sidebar
    type: textbox
  open-graph: true
  page-navigation: true
  repo-url: https://github.com/probcomp/genjax
  repo-actions: [edit, issue]

  sidebar:
    logo: logo.png
    style: 'docked'
    border: true
    pinned: true
    align: center
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/probcomp/genjax
        text: 'GitHub repository'
    contents:
      - section: 'Basics'
        contents:
          - href: introduction/intro_to_genjax/intro_to_genjax.ipynb
            text: Intro to Gen + GenJAX
      - text: '---'
      - section: 'Intermediate'
        contents:
          - href: intermediate/intro_to_combinators/intro_to_combinators.ipynb
            text: Generative function combinators
          - href: intermediate/incremental_computation/incremental.ipynb
            text: Incremental computing
          - href: intermediate/gradient_interfaces/gradient_interfaces.ipynb
            text: Differentiable programming
          - href: intermediate/gaussian_processes/gaussian_processes.ipynb
            text: Gaussian processes
      - text: '---'
      - section: 'Advanced'
        contents:
          - href: advanced/recurse_combinator/recurse_combinator.ipynb
            text: Recurse combinator
          - href: advanced/smc_language/smc_language.ipynb
            text: SMC inference DSL
          - href: advanced/pseudomarginal_smc/pseudomarginal_smc.ipynb
            text: Composable programming with approx. densities
      - text: '---'
      - section: 'Internals'
        contents:
          - href: advanced/impl_builtin_language/impl_builtin_language.ipynb
            text: Probabilistic semantics via interpreters

  page-footer:
    left: © Copyright 2022 [MIT Probabilistic Computing Project](http://probcomp.csail.mit.edu/)
    right:
      - icon: github
        href: https://github.com/probcomp/genjax

toc: true
toc-location: right
reference-location: margin
citation-location: margin

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [cosmo, custom-dark.scss]
    mainfont: 'Atkinson Hyperlegible'
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github

freeze: auto
