project:
  title: "GenJAX Jupyter notebooks"
  output-dir: ../_build/notebooks
  type: website

author: McCoy Reynolds Becker
theme:
  light: [simplex, custom.scss]

website:
  title: "Gen ⊗ JAX"
  search: 
    location: sidebar
    type: textbox
  open-graph: true
  page-navigation: true
  repo-url: https://github.com/probcomp/genjax
  repo-actions: [edit, issue]
  
  sidebar:    
    logo: logo.png
    style: "floating"
    contents:
      - section: "Basics"
        contents:
          - introduction/intro_to_genjax/intro_to_genjax.ipynb
      - text: "---"
      - section: "Intermediate"
        contents:
          - intermediate/intro_to_combinators/intro_to_combinators.ipynb
          - intermediate/incremental_computation/incremental.ipynb
          - intermediate/gradient_interfaces/gradient_interfaces.ipynb
          - intermediate/gaussian_processes/gaussian_processes.ipynb
      - text: "---"
      - section: "Advanced"
        contents:
          - advanced/impl_builtin_language/impl_builtin_language.ipynb
          - advanced/recurse_combinator/recurse_combinator.ipynb
          - advanced/smc_language/smc_language.ipynb
          - advanced/pseudomarginal_smc/pseudomarginal_smc.ipynb
  page-footer:
    left: © Copyright 2022 [MIT Probabilistic Computing Project](http://probcomp.csail.mit.edu/)
    right:
      - icon: github
        href: https://github.com/probcomp/genjax

toc: true
toc-location: right
reference-location: margin
citation-location: margin

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
    self-contained: true
    highlight-style: breeze
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 300px
