on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Run Nox
        run: nox

      - name: Build docs
        run: poetry run pydoc -o docs/ genjax

      - name: Deploy docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/
