name: Render and Publish Docs

on:
  pull_request:
  push:
    branches:
      - main
      - nightly

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install nox-poetry
        run: pip install nox-poetry

      - name: Run Docs Build
        run: nox -r -s docs-build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
