name: Render and Publish Docs

on:
  push:
    branches:
      - huebert/private-site

env:
  POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT: true

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # This works via GitHub's "deploy keys". This repo has a secret set up
      # with the private key, and the mkdocs-material-insiders clone in the
      # library has the public key set as a deploy key.
      - name: Configure SSH key for mkdocs-material-insiders
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.INSIDER_SSH_KEY }}
            ${{ secrets.MKDOCSTRINGS_PYTHON_SSH_KEY }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install nox-poetry
        run: pip install nox-poetry

      - name: Cache Nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-nox

      - name: Run Docs Build
        run: nox -r -s docs-build

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2.1.3'
        with:
          project_id: 'probcomp-caliban'
          workload_identity_provider: 'projects/110275315150/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
          service_account: 'gen-website-private-admin@probcomp-caliban.iam.gserviceaccount.com'
          audience: '//iam.googleapis.com/projects/110275315150/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'

      - name: Deploy to Google Cloud Storage
        run: | 
          WEBSITE_DIR='./site'
          PARENT_DOMAIN='gen.dev'
          SUBDOMAIN=${{github.event.repository.name}}
          BUCKET_PATH="gs://gen-website-private/$PARENT_DOMAIN/$SUBDOMAIN"
          gcloud storage rsync --recursive --delete-unmatched-destination-objects --cache-control 'public, max-age=60' $WEBSITE_DIR $BUCKET_PATH
