name: Pyright type checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pyright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5

      - run: poetry self update && poetry self add keyrings.google-artifactregistry-auth

      - run: poetry install --with dev --all-extras

      - uses: jakebailey/pyright-action@v1
        with:
          pylance-version: latest-release
