name: safety

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "nightly"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Install poetry/nox-poetry
        run: pip install poetry nox-poetry

      - name: Run Nox
        run: nox -s safety
